server:
  port: 8093
  servlet:
    context-path: /api/gateway
management:
  server:
    port: 8193
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: gateway
    version: @project.version@
  profiles:
    active: local

eureka:
  client:
    defaultZone: http://localhost:8761/eureka/
  instance:
    appname: clinic_service


