server:
  port: 8090
  servlet:
    context-path: /api/clinic
management:
  server:
    port: 8190
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
#    url: jdbc:postgresql://localhost:6438/postgres
    username: user
    password: password
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: pet-clinic
    version: @project.version@
  profiles:
    active: local

eureka:
  client:
    defaultZone: http://localhost:8761/eureka/
  instance:
    appname: payment_service


