server:
  port: 8093
  servlet:
    context-path: /api/mongo
management:
  server:
    port: 8193
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: mongo_service
    version: @project.version@
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Mongo_test
      username: root
      password: root
      authentication-database: admin



eureka:
  client:
    defaultZone: http://localhost:8761/eureka/
  instance:
    appname: mongo_service


